language: r
r: 
 - 3.6.1
dist: xenial
services:
  - xvfb
cache:
  packages: true
  directories:
    - _bookdown_files
    - $HOME/.npm
    
latex: false
pandoc_version: 2.7.2

env:
  global:
    - MAKEFLAGS="-j 2"

addons:
  apt:
    packages:
      - ghostscript
      - imagemagick
      - optipng
      - graphviz
      # magick
      - libmagick++-dev
      # pdftools
      - libpoppler-cpp-dev
      # rgl
      - libglu1-mesa-dev
      - libnlopt-dev
      - graphviz
      # sf
      - libudunits2-dev	
      - libproj-dev 	
      - libgeos-dev 	
      - libgdal-dev
      - ggobi
      - libgtk2.0-dev

script:
  - mkdir -p _book/interactives && cp -r interactives/* _book/interactives
  - Rscript -e 'bookdown::render_book("index.Rmd")'

after_success:
  - npm install netlify-cli -g
  # deploy with messages 
  - export COMMIT_MSG=$(git log -1 --format='%h %<(50,trunc)%s')
  - echo $COMMIT_MSG
  - export DEPLOY_MSG=${COMMIT_MSG//[\'\"\`]/}
  - echo $DEPLOY_MSG

deploy:
  provider: script
  script: netlify deploy --prod --dir _book --message "$DEPLOY_MSG"
  skip_cleanup: true
  on:
    branch: 
      - master
      - second-edition
