version: "3.6" # Docker Engine 18.02.0+
services:

   book:
     image: xiangyunhuang/msg-book
     container_name: msg
     command: 
       - /bin/bash
       - -c
       - |
         sh ./_build.sh
         xvfb-run make pdf
     environment:
       - TRAVIS
       - PWD
       - MAKEFLAGS
       - DISPLAY
     volumes:
       - ${PWD}:/home/docker/workspace
