# 古统新修记（代序） {#forword2 .unnumbered}

> 　　古统者，古代统计图形也，乃谢公益辉所著现代统计图形之谑称。盖其成书甚早，初出即声名大噪，黄发垂髫莫不读之后快。然久未付梓，仅手抄本[^pdf]辗转相传于坊间，其间桃花人面，沧海桑田，忽忽十载，现已作古，遂有古统之誉。

[^pdf]: 即 pdf 版。

> 　　古统之手抄本，始于丁亥[^2007]，发于戊子[^2008]，兴于己丑[^2009]，终以庚寅[^2010]本传世。庚寅者，凡八十回，二百一十页，六十五图，盖八章：历史、工具、细节、元素、图库、系统、模型、数据。另附导读、程序初步、作图技巧、统计动画、本书 R 包。回目有笑傲[^xiaoao]之韵，或兼射雕[^shediao]之风。彼时 R 语言初入中原，小荷乍露，凡读古统者，无不惊诧于 R 语言之惊艳，著者之渊博，文笔之雅致，洞见之深远。然系统、模型、数据三章空有其骨，未见其肉，如夜归掷履，邻人闻落地声一，待其二者，终不得焉，念之，憾之，恨之，盼之。

[^2007]: 即 2007 年。
[^2008]: 即 2008 年。
[^2009]: 即 2009 年。
[^2010]: 即 2010 年。
[^xiaoao]: 金庸《笑傲江湖》，每章标题均为两个字。
[^shediao]: 金庸《射雕英雄传》，每章标题均为四个字。

> 　　戊戌[^2018]至，著者谢公自云[^blog]，乃为生计所迫[^phd]，或为良墨之缺[^lyx]，古统残本实难为继，遂传辛卯[^2011]本。辛卯者，增页减章，凡七章八十回：历史、工具、元素、图库、系统、数据、元素，古意犹存。三百六十五页，含二表，百卅八图，较庚寅本倍之。尤以图库、数据二章所增为善。天下饥久，今解朵颐之快，遂喜大普奔。时有 ggplot 丹青风靡，人尽逐之。古统虽有述及，奈何以古法为尊，修之无肉，弃之有味。著者遂弃。天下闻之，莫不扼腕长叹。盖虽残本，世间莫有他作与之比肩者矣。

[^2018]: 即 2018 年。
[^blog]: <https://yihui.org/cn/2018/09/inbox-zero/>。
[^phd]: 据说是忙于博资考。
[^lyx]: 据说是所用的文本工具崩溃了。
[^2011]: 即 2011 年。

> 　　辛卯毕，手抄一。bookdown 兀，己亥[^2019]出。有黄公湘云者，得谢公雅量赐手稿，乃以迅雷之势，着良墨[^bookdown]于旧稿，迁[^move]手稿于新址，时人异之，不知良墨实为谢公所创。古统新址，人皆可访之；良墨旧稿，人皆可修之。群雄遂起，竞相争鸣，张公列弛、曹公讳洋增 ggplot 新图，古统乃复见现统之大观。圣人曰：独乐乐，与民乐乐，孰乐？黄公之功，善莫大焉。

[^2019]: 即 2019 年。
[^bookdown]: <https://bookdown.org/yihui/bookdown/>
[^move]: <https://d.cosx.org/d/420857>

> 　　古统八十回之残本，如曹公之石头记，或断臂之维纳斯，美则美矣，终为不全之数，天下憾之久矣。今余受谢黄二公之托，重修现统，以付梓为盼。十年之功，毕此一役，余知兹事体大，如红楼续梦、美神接臂，临深履薄，诚惶诚恐。虽肝脑涂地，未敢不尽心竭力。夙夜披阅，五次增删，终得庚子本。凡一十一章。插图皆以 ggplot 新绘，增至百五十图，廿五表，页四百余。

> 　　嗟乎！余幼年慕周公华健之声，后习丝竹，遂于京师学堂有与周公同台之乐。今壮年习 R，独行步履维艰，恰逢谢公古统庚寅本出，旱逢甘露，受益匪浅。未料日后拙作《学 R[^xuer]》得谢公赐序。今复为其旧作新修，世事之玄妙莫过于此。古人不见今时月，今月曾经照古人。人生如露，大梦十年，天下豪杰，岂不笑我辈痴绝耶？

[^xuer]: <https://xuer.pzhao.org>

> ——赵鹏 于 姑苏西浦
