--- 
title: "现代统计图形"
subtitle: "Modern Statistical Graphics"
author: 
  - 赵鹏
  - 谢益辉
  - 黄湘云
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography:
  - book.bib
  - MSG-packages.bib
  - Modern-Stat-Graphics.bib
biblio-style: plainnat
natbiboptions: "authoryear,square"
link-citations: yes
graphics: yes
mathspec: yes
lot: yes
lof: yes
classoption: "UTF8,twoside"
papersize: b5
colorlinks: yes
geometry:
  - tmargin=2.5cm
  - bmargin=2.5cm
  - lmargin=3.5cm
  - rmargin=2.5cm
description: "现代统计图形书稿"
subject: "统计图形, 数据可视化"
keywords: 
  - R 语言
  - 统计图形
  - 统计学
  - 图形元素
  - 图形系统
  - 统计图形软件
  - 数据可视化
github-repo: XiangyunHuang/msg
url: 'https\://bookdown.org/xiangyun/msg/'
---


# 推荐语 {#welcome .unnumbered}

互联网技术革命对统计学之影响是向人类社会量化解析自然生态和社会生态的深度进军，广义统计是一个深入发展统计思想期待的重心，其中，最为突出的具有龙头发展地位的是广义统计系统数据信息的可视化，它是当今人类社会发展在互联网平台化所有领域中实现认知、社会学习、分析研究、系统应用扁平化的科学手段。面对可视化的“现代统计图形”，可以适应任何人所拥有知识起点之认知学习，激发社会化学习研究之创新，对所有学科知识交叉应用可以升起不落的“发展力太阳”。对此，《现代统计图形》做出了杰出的贡献。

```{block2, type = 'flushright', html.tag = 'p'}
赵彦云  
中国人民大学统计学院教授
```

我认识老谢有 19 年了，等这本书的出版就等了 14 年。我在工作、学习中从这本书里获得了很多灵感，我自己写的书里也多次引用了这本书网络版的内容。这不仅是一本统计图形的工具书和参考书，更可以作为统计思维的人生之书。

```{block2, type = 'flushright', html.tag = 'p'}
李舰  
统计之都理事，《统计之美》作者，九封医疗首席数据科学家
```

《现代统计图形》的雏形始于 2007 年，那一年我还在中国人民大学统计学院读大四，益辉师
兄（老谢）比我高一级。他能坚持 14 年把书稿高质量地呈现给读者，彰显着现代统计人的初心。

这本书以浅显而有趣的图形示例将统计学和可视化的历史娓娓道来，是一本难得的以图形为主线、探讨统计学和统计可视化的高质量通识读物。书中内容无不体现作者对现代统计和统计图形的深刻思考，例如“神奇数字”和“作图原则”等章节。这本书既可作为高校师生的统计计算或者统计软件中可视化章节的主要参考书，也可作为严谨学术作图的指导手册。

```{block2, type = 'flushright', html.tag = 'p'}
李丰  
中央财经大学统计与数学学院副院长、副教授
```

缺乏信心作出预期的图形吗？希望用 R 基本代码随意生成任何图形吗？欲用“半傻瓜”方法 构造漂亮而又时髦的图形吗？渴望知道图形背后的原理及数学吗？愿意把画图作为乐趣吗？想 要轻松地阅读一本关于编程软件的书吗？答案很简单：读这本《现代统计图形》!

```{block2, type = 'flushright', html.tag = 'p'}
吴喜之  
中国人民大学统计学院教授
```

纷繁嘈杂的数据经过科学的处理、加工之后，映入眼帘的是生动、直观、一图胜千言的统计图形，这个美妙的过程称为可视化分析，是数据科学中极为重要的部分。

益辉兄的这本《现代统计图形》不仅高屋建瓴，概述了可视化分析的前世今生和哲学理念。 同时，内容包罗万象，精彩纷呈。从最常用的条形图、直方图，到根据不同场景和数据自定义图 形；从各种图形的思想和理论，到具体的案例和代码；从作图的细节参数，到不同的作图框架； 处处闪耀着智慧的火花，令人目不暇接，收获颇丰。

本人有幸在 10 年前，参与了这本书初稿的审阅校对，更有幸的是 10 年后，亲眼看见这本书 正式与读者见面。甚为欣慰，特此推荐。

```{block2, type = 'flushright', html.tag = 'p'}
魏太云  
统计之都理事会第二任主席
```


这本书是我读过的最有意思、最吸引人的关于统计图形的书。我想，无论是否了解图形可视 化，是否是统计专业人士，是否有 R 语言编程经验，都能从这本书中发现许多有价值的内容并从 中受益。这本书在介绍常用统计图形的同时，用实例深入阐述各种图形的用法和含义，指导我们 如何选择和使用统计图形，在授人以鱼的同时授人以渔。

```{block2, type = 'flushright', html.tag = 'p'}
曹洋  
博士，生物信息分析师
```


看这本书之前我以为 R 语言我算入门了，看完之后深感自己的无知。

```{block2, type = 'flushright', html.tag = 'p'}
姜军  
武汉大学临床医学在读博士研究生
```


优秀的统计思想和统计方法需要优雅的统计图形来表达。《现代统计图形》使用鲜活的经典 实例深入浅出地阐释了统计图形的设计原则，给出了一套全面且实用的参考图库与绘图技巧，理 论与实践并重，值得科研人员和数据科学从业者常备和参考。


```{block2, type = 'flushright', html.tag = 'p'}
肖楠  
默沙东实验室生物统计和研究决策科学部副主任科学家
```

读完此书，耳目一新。这本书开篇从统计作图的历史娓娓道来，中间辅以实例系统地介绍了 不同类型的统计作图，最后从心理学角度总结了作图的原则。读者可以深切地感受到作者对数学 生命的敬畏和热忱。全书既融汇了科学与艺术，又十分接地气，是同类书中极为难得的一种存在。


```{block2, type = 'flushright', html.tag = 'p'}
吴晟  
暨南大学质谱仪器与大气环境研究所副研究员
```


大数据统计或挖掘结果的图形化，是人们快速观察并发现数据隐藏信息或新颖知识的有效方法。统计图形不仅是大数据统计和挖掘结果的可视化利器，也是高水平学术成果的重要组成部分。
《现代统计图形》集趣味性、知识性、技术性和实践性于一体，是作者浓缩多年用 R 语言制作统 计图形经验的匠心之作。这本书不仅可作为高校统计学、数据科学与大数据技术等专业本科生的选修课教材，也可作为高校硕士和博士研究生用 R 语言作图的快速入门参考书。利用这本书提供 的 R 语言作图源程序，读者可轻松掌握其基本方法，并在不知不觉中快速成长为使用 R 语言及 其绘图包 ggplot2 制作统计图形的高手。


```{block2, type = 'flushright', html.tag = 'p'}
黄德才  
浙江工业大学教授、博士生导师，资深数据科学专家，
“十一五”“十二五”国家级规划教材作者，浙江省教学名师
```

数据可视化的学习之中，存在“道”与“术”两个不同层面。“术”为工具的使用，包括程序语言、作图函数等；“道”为作图思想，是逻辑、统计知识、审美等多方面的综合。这本书极难得地将二者相结合，不空谈道，也不局限于术。在每个阶段读，都有不同的收获。同时，还辅以百余种常见统计图形为案例解析，实乃不可多得之佳作。

```{block2, type = 'flushright', html.tag = 'p'}
王建栋  
南京信息工程大学大气物理学院教授
```

翻开这本书，不会觉得自己在念教材，也感觉不到科技制图“严谨性”带来的束缚，更像是
在和几位艺术家聊天，畅谈研究数据的美学呈现。

```{block2, type = 'flushright', html.tag = 'p'}
王小享  
南方科技大学研究助理教授
```

如果你一直在寻找一本能循循善诱带你入门，又能一路托你到卓尔不群的统计图形真经，就 是这本《现代统计图形》。但是作者们并非仅仅醉心于打造一本“图形形式美”的工具辞典，对 贯通数学原理与图形表达，从认知逻辑出发优化视觉传达，权衡图形的直观呈现与统计价值等问题的思考暴露了三位作者的“数学艺术家”本质。木心有句：“思维、情操的创造性必然伴随着形式的创造性。”说的就是这些人、这本书吧。

```{block2, type = 'flushright', html.tag = 'p'}
刘倩  
中央财经大学财经研究院副研究员
```

这本书溯流从源地带着读者领略数据可视化技术的本质之“道”：可视化终究是数学的直观图形表达，而熟练偏向底层的技术才能使得表达过程不受束缚。即使这本书被谢大拖稿 14 年，依然被众多读者千呼万唤始出来，足见其超越技术本身，而道出数据可视化之本质的价值。

```{block2, type = 'flushright', html.tag = 'p'}
夏骁凯  
华南师范大学计算认知科学博士研究生
```

统计学及统计可视化是当前大数据时代最炙手可热的学问。如何挖掘数据价值，让数据直观 地呈现并为我们所用，数据可视化功不可没。值得思考的是，我们所使用的可视化展现方式是否 清晰准确地表达出了数据背后的价值。对于大部分人来说，Excel 是办公场合使用最多的软件， 几乎垄断了我们的日常工作。然而，这种数据可视化方式具有局限性，限制了统计工作者想要自 定义统计图形的“能动性发挥”，可视化效率不高。相较于其他作图软件，R 语言具有极强的“可 定制性”。《现代统计图形》以风趣幽默的语言、浅显易懂的图形案例介绍了统计图形的历史，从应用角度全面介绍了 R 语言作图及其绘图包 ggplot2 作图的源程序，详细讲述了 R 语言作图系统 中的各个细节，让我们由浅入深地掌握数据可视化的精髓。读者在这本书中不仅能学到 R 语言制 作统计图形的实用技术，还可以拓展制作统计图形的探索性思维。对于初学 R 语言的众多科研工 作者来说，这本书实在是不可错过的入门启蒙书。

```{block2, type = 'flushright', html.tag = 'p'}
于志国  
南京信息工程大学水文与水资源工程学院副院长、教授、博士生导师
```

《现代统计图形》读起来就像一本由武林前辈撰写的兵器图谱，其中不仅包含兵器（R 作图 元素及工具）展示、武功心法（统计学知识及作图原则），更有不少江湖趣事（统计图形简史及 案例分析）。不管你是江湖少侠（熟悉 R 或统计学），或者初入江湖（刚开始学习 R 或统计学）， 我相信这本书都能帮你提高一层境界。即便是如我一般的小白，也多半会被作者们幽默诙谐的语 言、娓娓道来的叙述，以及层层递进的剖析深深吸引，而受益匪浅。

```{block2, type = 'flushright', html.tag = 'p'}
叶飞  
纽约城市大学数学助理教授
```


喜欢谢益辉的人很多，但要认识真实的谢益辉或许要从这部作品开始。他对统计艺术的赤诚 态度、对统计可视化创作的厚积薄发，这在人大统计专业我所教过的毕业生中并不多见。统计之 灵借着益辉通俗的文字、生动的图形和缜密的语言对我们低语，传达着一代青年统计学者对数据 之美的追求、对科学信念的执着，和他独特的对数据垃圾与艺术作品差别的关注与思考，《现代 统计图形》值得关注。


```{block2, type = 'flushright', html.tag = 'p'}
王星  
中国人民大学统计学院副教授，《中国大百科全书》第三版统计学卷编委
```

这是一本“时间的玫瑰”，历久弥新，芬芳四溢。

写书之人向读书之人表达尊重的最高级方式是行文如流水，专业功底隐藏在明晰简练的文字 之下。读这本统计图形的专著，感觉不到图形与文字间的隔阂，也感觉不到有意或无意间的权威 性。书中用“我们”的口吻表达作者与读者间平等的沟通关系。

作者亦非常注重美感，读者从书的排版、布局、文字、图形和颜色的区分等方面都可以感受 到美的力量。

了解或熟知谢益辉其人的读者，从此书中可读出作者青春的印记，“四时可爱唯春日，一事能狂便少年”。完全陌生的读者，看到此书便是缘分，愿你在运行书中代码、思考作者提出的小结问题之中，获得启蒙。

```{block2, type = 'flushright', html.tag = 'p'}
李承文  
不懂统计学的平常百姓
```

谢益辉是 R 扩展包 bookdown 的作者，他和两位合作者的这本新书可以作为学习 R 统计图形的教材和参考手册，其中许多图形是现有中文 R 语言教材中没有涉及的。书中还精练、准确地概 括了 R 基础作图、ggplot2 作图系统，并用许多饶有趣味的实例深入浅出地介绍了重要的统计图形 原则。

```{block2, type = 'flushright', html.tag = 'p'}
李东风  
北京大学数学科学学院副教授
```

在我的理解中，统计分析的过程和把大象关在冰箱里的步骤是一样的。第一步，把庞杂的原 始数据整理成统计软件可以接受的形式；第二步，运用恰当的方法进行分析；第三步，通过图形 等方式，把结果表达为人类便于理解的形式。我们的教育只重视第二步，导致很多人于实际中在 第一步和第三步中遇到了困难。对于第一步，必须要学习一门处理数据的语言，比如 R。而对于 第三步，一直以来没有很好的解决方案，直到这本《现代统计图形》的出现。

```{block2, type = 'flushright', html.tag = 'p'}
姜晓东  
湖南师范大学医学院讲师
```

我们已经进入了眼球经济时代，获得注意力就是获得财富。在我多年指导学生的实践中，越 发感受到图对于提升科研成果价值的重要性。今日翻开《现代统计图形》，如获至宝。作者深入 浅出地将枯燥的作图工具娓娓道来，一张张精美的图片更映射出作者的情感、心境和人生态度。相信这本书定能使广大读者发现作图的快乐!

```{block2, type = 'flushright', html.tag = 'p'}
袁自冰  
华南理工大学教授、博士生导师
```

你或许追过周更的动漫，季更的网剧，年更的小说，但你追过十年更的《现代统计图形》吗?我追过。

惊闻被谢大戏称为“古统”的《现代统计图形》即将问世，一时竟有不知今夕何年之感。翻 了翻过去的通讯记录，发现整整十年前谢大曾发了封邮件，问道：“你最近有空帮我写两节书 吗?”从此我知道了这本书的存在，并开启了长达十年的催更之路。

谢大所谓“古统”虽是戏谑之语，但也能读出其中的疑问：什么是统计图形的现代元素？按我的理解，统计图形最大的价值就在于它能加深人们对其背后数据的认识，而现代与否，关键在于图形能否为数据和问题提供了新的思考和解读。“图”虽旧“码”，其命维新。相信在阅读这本书后，读者会得益于其中的“探案过程”，学会用统计图形这一强大的工具去探究数据背后的秘密。

```{block2, type = 'flushright', html.tag = 'p'}
邱怡轩  
统计之都理事，上海财经大学青年教师
```

赵鹏老师的博客“大鹏志”曾陪伴我走过学 R 语言最为艰难的一段时光。他用虽朴实无华但 不失风趣的语言，以讲道理的方式，循循善诱地告诉你为什么如此做、应该和可以怎么做。此后 出版的《学 R：零基础学习 R 语言》更是让我爱不释手、如获至宝。而打开《现代统计图形》之后，惊叹图形在 R 语言中可以如此被“调教”，一步步地跟着这本书的思路走，相信每个人都可以找到属于自己风格的绘图方式，特此推荐。

```{block2, type = 'flushright', html.tag = 'p'}
杨雷峰  
博士，生态环境部华南环境科学研究所研究员
```


多年后，面对即将出版的《现代统计图形》，我不禁回想起，在网上初见其书稿的那个遥远 的下午。

我想，当年看过网上流传的《现代统计图形》书稿的人大多应该和我一样，一直盼着它的正 式出版，然而，作者一“鸽”就是多年（后来才听说原来是磨刀去了 —— knitr、bookdown），直到最近终于要成书了。R 作为一门为统计而生的语言，长处之一就是其灵活的作图系统 —— 正所谓一图胜千言，有比把枯燥的数字变为漂亮的图形更好地展示统计思想的方法吗？然而 R 作图系统的灵活和强大也带来了相对陡峭的学习曲线。在《现代统计图形》里，作者们用流畅风趣的 语言为读者讲解构成图形的元素，并展示在 R 里如何将它们组合起来表达统计思想，在降低学习难度的同时，还为学习统计图形增添了许多乐趣。

书稿诞生后的这些年里，R 的江湖里兴兴废废出现了各种作图系统。大浪淘沙后，现在最常使用的除了 R 的基础作图系统外，就是 ggplot2 了。在这本书中，作者们不仅介绍了各个作图系统，还展示了用基础作图系统和 ggplot2 实现相同图形的代码。R 的基础作图系统和 ggplot2 在作 图上各有千秋，用这两种方式实现同一图形能更好地让读者体会各系统的优劣，以便在自己的数 据分析中选用合适的方式绘制图形。


```{block2, type = 'flushright', html.tag = 'p'}
张列弛  
日本基础生物研究所技术支援员
```

第一次看到《现代统计图形》的书稿大约是在 10 年前，当时惊艳于它对统计图形全面、系统的讲解，惊为天人。10 年后，重读此书——即便 ggplot2 已经成为统计图形的标配，但我们依然可以从问题到数据、数据到图形的诸多案例中明白：为什么呈现的图形是这个样子。该书分门别类地讲述了统计图形的图库、准则和系统，字里行间传递的“为什么”则更为精彩，正本溯源是《现代统计图形》最大的价值。如果读者第一次阅读此书，相信也会和我 10 年前的感受一样，enjoy it !

```{block2, type = 'flushright', html.tag = 'p'}
刘思喆  
51Talk 首席数据科学家
```

信息爆炸，数据称王，好文章不看辞藻看图表。这本书好似一本秘籍，照着例子依猫画虎， 可练外功，任意数据均可成图做表；照着目录由简入繁，可获内功，枯燥数据变成生动图表。所 有和数据打交道的人，都值得入手一本，需要的时候翻翻。你会发现这本书不需要全部读懂，读 半本就可治天下图表。

```{block2, type = 'flushright', html.tag = 'p'}
陈正  
西交利物浦大学健康与环境科学系副教授
```

作为科研成果展示形式的关键组成部分，作图发挥着不可替代的重要作用。当今很多顶级 期刊采用的论文，大多配有恰如其分且赏心悦目的插图，这不仅有助于准确而深刻地表达学术 思想和结果，而且会令论文大为增色。为此，我向我的学生们推荐这本《现代统计图形》。这本 书细致入微地从基本的统计思想出发，详述了常见科技制图的理论和实例，是我的学生赵鹏继
《学 R：零基础学习 R 语言》一书出版后，与另外两位作者合著的又一力作。


```{block2, type = 'flushright', html.tag = 'p'}
朱彤  
北京大学教授、博士生导师，北京大学环境科学与工程学院院长
```

可视化是人与数据沟通的桥梁，也是人类观察数据世界的放大镜。可视化相关的教材很多，很多描绘了通过可视化看到数据的种种绚丽多彩的画卷，但是很少能向读者详细解释如何构建这样的“放大镜”。从这一意义上来说，这本作者聚十四年之力而作的《现代统计图形》尤其值得推荐。它不只介绍了可视化的概念和方法，书中对每一个常用的可视化方法都给出了 R 语言的实验细节，这是很多可视化实践者的福音。这本书的发行，必将极大地促进可视化的推广和应用。


```{block2, type = 'flushright', html.tag = 'p'}
袁晓如  
北京大学“百人计划”研究员，北京大学信息科学技术学院博士生导师
```
