# 模型 {#cha:model}

> “嗯，人的身高十有八九可以从他的步幅的长度推测出来，这极容易推算，但是让我把枯燥的数字摆出来算给你看实在是毫无用处。我在屋外的粘土路上和屋内的尘土上找到了那人的脚印，此外我还有一个法子验证我的计算：当一个人在墙上写字时，他会本能地将字写在视线以上的地方，而那个血字正好离地面六英尺。这推算实在是简单得像儿戏一般。”
>
> 我问：“那他的年龄呢？”
>
> “好的，如果一个人不费吹灰之力就能一步跨出四英尺半，他不可能年老体衰，因为花园小径上的泥坑恰好长四英尺半，他显然是一步跨过去的，漆皮靴则是绕过去的，所以这也没有什么神秘之处。我只不过是将我在那篇文章中推崇的一些观察和演绎的规则应用在日常生活中罢了。你还有什么不明白的地方吗？”
>
> --- 柯南·道尔《血字的研究》

在 \@ref(sec:begin) 小节中我们曾经提到三种基本的统计分析方式，其中包括推断统计分析和探索统计分析，表面上看来，统计模型在前者中占主导地位，而统计图形在后者中往往起着非常重要的作用，然而本章要探讨和揭示的则是以探索为目标的统计图形与以推断为目标的统计模型之间的联系。

## 线性模型 {#sec:lm}

- 一元回归：散点图
- 回归诊断：方差齐性假设、线性假设、独立性假设、正态性假设、离群点

## 方差分析 {#sec:aov}

- 类似回归
- 箱线图等

## 局部加权回归散点平滑法 {#sec:lowess}

`lowess()` `loess()` `scatter.smooth()` `runmed()` ? 

[用局部加权回归散点平滑法观察二维变量之间的关系](https://cosx.org/2008/11/lowess-to-explore-bivariate-correlation-by-yihui)

## 稳健回归模型 {#sec:rlm}

- 离群点

## 广义线性模型 {#sec:glm}

- 回归诊断

## 线性混合效应模型 {#sec:lme}

Gelman 讲“为啥不关心多重比较的问题”：<https://stat.columbia.edu/~gelman/presentations/multiple_minitalk2.pdf>（随机效应模型究竟做了什么？）

## 主成分分析和因子分析

- 成分方差
- Biplot

## 聚类分析 {#sec:cluster}

- 谱系图
- K-Means 的散点图
- 基于密度的聚类

## 判别分析

- 成分的散点图
- LDA/二次判别分析

## 多维标度分析

`cmdscale()`, `isoMDS()`

- 高维数据的二维（低维）表示

## 时间序列分析

经典 ARMA、谱分析等

自相关 `acf()` 偏自相关 `pacf()` 时滞图 `lag.plot()`

累积周期图 `cpgram()`

## 空间分析

克里金插值

样本变差图

变差云图



