# 后记 {#postscript}

2007 年 2 月，我在家读 A Handbook of Statistical Analysis Using R [@Everitt06]，书中读完前八章之后，萌发了写一篇关于统计图形综述的念头，于是用 LaTeX 匆匆写了几页，但几天后发现这不是一篇综述能讲清楚的事情，于是改为写一本三十来页的小册子，依次介绍 R 语言中的那些基本的统计图形，然而几天后发现这也不是一本小册子能装得下的内容，因为当时国内统计界对 R 语言的了解相对较少，所以有必要把统计图形放在整个 R 的系统下来讲述，于是在几经折腾之后，写这本书的念头诞生了。

如我在 \@ref(sec:begin) 小节中提到的，国内统计图形应用的现状并不是很理想，然而，在这本书中，我结合大量的数据实例给出了各式各样统计图形的展示，其中有相当一部分图形在我们的论文、书籍或报告中并不常见，原因是什么我并不太清楚，也许受软件束缚，也许并不知道有这些图形的存在，无论如何，本书作为一本指南读物，对软件实现以及图形种类都做出了介绍，对统计图形的问题也算是提供了一种解决方案，不过我的主要目的并不在于单纯介绍图形，而是想借现有的图形思想启发读者，一方面使读者能够明白图形的基本构造方法，这样可以让我们容易就能借“它山之石”为自己所用，即看到别人的好图形，自己便知道如何去做；另一方面希望读者通过观摩各种图形的思想，在自己的数据分析过程中找到图示的灵感，用更巧妙的方式揭示信息。

国外的统计图形和可视化水平相对国内看起来要领先许多，我于 2008 年 6 月在德国不来梅的 Jacobs 大学参加了一个统计图形会议（Data Viz VI），见到了统计图形领域的一些“长老”和新秀，如第\@ref(chap:principle)章提到的 Michael Friendly，这位老爷子在统计图形上作了大量工作，尤其是分类数据的可视化以及统计图形历史的总结等等，我正是从他那里了解到了统计图形的一些历史，包括本书第\@ref(cha:history)章介绍的图形；参会的还有 AT\&T 统计研究部门的 Deborah Swayne、Iowa 州立大学的 Di Cook （目前已经是我的导师）、沃顿商学院的 Andreas Buja （ [GGobi](http://www.ggobi.org) 最初就是他们三人合作写出来的）、Systat 公司的 Leland Wilkinson （The Grammar of Graphics 的作者）， 同时我也见到了一些年轻学者如 Hadley Wickham （**ggplot2** 包的作者）、Michael Lawrence （**RGtk2** 包的作者）等；通过与这些人的接触，我进一步意识到了国内在统计图形方面和国外的差距，回来之后更加坚定了我完成这样一本统计图形书籍的信念。

2008 年到 2009 年这本书进展到了第\@ref(cha:gallery)章，也就是图形的海洋，这一章耗费了很长时间，因为内容几乎是无止境的。实际上到了 09 年进展就很慢了，这一年夏天来到了 Iowa 州立大学，渐渐搁置了这本书几乎没再动过笔。2010 年 5 月，周筠老师闯进了我的邮箱（我以前隐约听说过她，但没正式联系过），问起这本书，对话非常简单，几乎可以缩写为：

> 我：“中不？”

> 周：“中！”

> 我：“好，归你了！”

于是乎，我的 CPU 又开始轰隆隆运转起来。

在 Iowa 州立大学的学习让我更新了不少知识，尤其是在两位专家 Di Cook 和 Heike Hofmann 的影响下。原本这书的目标只是介绍基础图形系统，也就是第\@ref(cha:elements)章和第\@ref(cha:gallery)章的内容，但随着知识的积累和 R 自身的更新，写着写着我就感觉落后于时代了，书名中有“现代”二字，如果只是基础图形系统，那么实在不敢称“现代”，所以在完成第\@ref(cha:gallery)章之后，我加入了第\@ref(chap:system)章内容，这样起码在工具上有点现代的感觉，例如 ggplot2 和动画，都是 R 里面的新事物。纯粹的工具介绍对读者来说可能会显得枯燥，尽管大部分图形都有对应的数据，但那些数据往往都是很老旧的数据，人人皆知；Cook 经常对我“怒吼”：No more `iris` data！！她对我使用旧数据有一肚子不满，我想这大概可以代表一部分读者的心情，于是这本书有了第\@ref(chap:data)章，我尽力找了新数据，要说它们有多新呢？图 \@ref(fig:pork-price-orig) 是我 2011 年 2 月 22 日收到的邮件，23 日我把它写进了书里。第\@ref(chap:principle)章放在最后作为所有技术性内容之后的一个总结，但它实际上也交织着技术性内容；我在导读中引用了“形而上者谓之道，形而下者谓之器”，实际上我觉得道与器无法分家，这道理就像“学而不思则罔，思而不学则怠”一样。

本书每章开头都挑选了一段《福尔摩斯探案集》中的文字，其内容与各章内容有一定关联，这也是由于我个人在上高中时就喜欢看福尔摩斯，并且我认为统计图形也可以看作是一种小小的“探案”。探案集中我最喜欢的一篇是《血字的研究》，尤其欣赏该篇的第二部分中大篇的景色描写，以及对主人公杰弗逊 $\cdot$ 霍普坚韧不拔性格的刻画，这种波澜壮阔的笔法，令我着实艳羡不已，只可惜我没这种文字功夫能把书写得如此吸引人，于是只能寄希望于“一图胜千言”了。

诗云：人事有代谢，往来成古今。江山留胜迹，我辈复登临。

